spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visitmanager
    username: guilherme
    password: 2102@guisio
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret:
    MYJWTSECRET
  expiration:
    3600000